import JSZip from 'jszip';
import type { ImageAsset, SiteProject } from '@/types/project';
import { renderSite } from './render';
import { imagePath } from './seo';

const FAVICON_SVG = (project: SiteProject) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="${project.brand.primaryColor}"/><text x="50%" y="58%" text-anchor="middle" font-family="system-ui, sans-serif" font-size="16" font-weight="700" fill="${readableTextColor(project.brand.primaryColor)}">${initials(project.business.name)}</text></svg>`;

function initials(name: string): string {
  const parts = name.trim().split(/\s+/);
  const first = parts[0]?.[0] ?? 'S';
  const last = parts.length > 1 ? parts[parts.length - 1]?.[0] ?? '' : '';
  return (first + last).toUpperCase();
}

function readableTextColor(hex: string): string {
  // Tiny dup to avoid pulling color.ts here; this is good enough for a 32x32 favicon.
  const h = hex.replace('#', '');
  const v = parseInt(h.length === 3 ? h.split('').map((c) => c + c).join('') : h, 16);
  const r = (v >> 16) & 255,
    g = (v >> 8) & 255,
    b = v & 255;
  const luma = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luma > 0.6 ? '#0b0b0b' : '#ffffff';
}

function dataUrlToBlob(dataUrl: string): Blob {
  const [meta, data] = dataUrl.split(',');
  if (!meta || !data) return new Blob();
  const mimeMatch = /data:([^;]+)(;base64)?/.exec(meta);
  const mime = mimeMatch?.[1] ?? 'application/octet-stream';
  const isBase64 = !!mimeMatch?.[2];
  if (isBase64) {
    const bin = atob(data);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
    return new Blob([arr], { type: mime });
  }
  return new Blob([decodeURIComponent(data)], { type: mime });
}

function collectAssets(project: SiteProject): ImageAsset[] {
  const seen = new Set<string>();
  const out: ImageAsset[] = [];
  const push = (a: ImageAsset | null | undefined) => {
    if (!a) return;
    if (seen.has(a.id)) return;
    seen.add(a.id);
    out.push(a);
  };
  push(project.brand.logo);
  for (const g of project.content.gallery) push(g);
  return out;
}

export async function buildZip(project: SiteProject): Promise<Blob> {
  const zip = new JSZip();
  const rendered = renderSite(project);

  zip.file('index.html', rendered.html);
  zip.file('assets/css/style.min.css', rendered.cssMin);
  zip.file('assets/css/style.css', rendered.css);
  zip.file('assets/js/main.min.js', rendered.jsMin);
  zip.file('assets/js/main.js', rendered.js);
  zip.file('sitemap.xml', rendered.sitemap);
  zip.file('robots.txt', rendered.robots);
  zip.file('project.json', rendered.projectJson);

  // Favicon — generated SVG so the export is self-contained.
  zip.file('assets/images/favicon.svg', FAVICON_SVG(project));

  // Images
  for (const a of collectAssets(project)) {
    const path = imagePath(a);
    zip.file(path, dataUrlToBlob(a.dataUrl));
  }

  // Netlify forms manifest — Netlify auto-detects forms in HTML, but we add a
  // brief notes file to make it obvious where the form lives.
  zip.file('NOTES.md', NOTES_MD(project));

  return zip.generateAsync({ type: 'blob' });
}

function NOTES_MD(project: SiteProject): string {
  return `# ${project.business.name} — generated by SiteForge

This folder is a self-contained static site, deployable as-is to Netlify, Vercel, GitHub Pages, or any static host.

## Deploying to Netlify
1. Drag this folder onto https://app.netlify.com/drop
2. The contact form is wired to Netlify Forms automatically (look in your site's "Forms" tab).

## Re-importing into SiteForge
Open the SiteForge builder and choose **Load project** → select \`project.json\` from this folder.

## Files
- \`index.html\` — generated, human-readable HTML.
- \`assets/css/style.min.css\` — production stylesheet (also served via \`<link>\`).
- \`assets/css/style.css\` — readable copy of the same stylesheet.
- \`assets/js/main.min.js\` — production script.
- \`assets/js/main.js\` — readable copy of the same script.
- \`assets/images/\` — all uploaded images (rename to \`.webp\` for further savings).
- \`sitemap.xml\` and \`robots.txt\` — generated for SEO.
- \`project.json\` — the full source-of-truth for re-imports.
`;
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    URL.revokeObjectURL(url);
    a.remove();
  }, 100);
}
